name = "bill-splitter-frontend"
compatibility_date = "2024-12-21"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "bill-splitter-frontend"

[env.preview]
name = "bill-splitter-frontend-preview"

# Build configuration
[build]
command = "pnpm run build"
cwd = "frontend"
watch_dir = "frontend"

# Pages configuration
pages_build_output_dir = "frontend/out"
