[package]
name = "bill-splitter-api"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = "0.0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3"
features = ["console"]
