[package]
name = "bill-splitter-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
cargo-watch = "8.5.3"
